### ISSUE TITLE
ValueError: 'latex' codec can't encode character '\u2009' in position 0: don't know how to translate '\u2009' into latex

### ISSUE THREAD

**Issue by leofang** [nschloe/betterbib#128]
Use BibTeX data from Crossref for DOI:10.1364/OPTICA.2.000832
```bash
$ echo "@article{Takesue_2015,
	doi = {10.1364/optica.2.000832},
	url = {https://doi.org/10.1364%2Foptica.2.000832},
	year = 2015,
	month = {sep},
	publisher = {The Optical Society},
	volume = {2},
	number = {10},
	pages = {832},
	author = {Hiroki Takesue and Shellee D. Dyer and Martin J. Stevens and Varun Verma and Richard P. Mirin and Sae Woo Nam},
	title = {Quantum teleportation over 100{\hspace{0.167em}}{\hspace{0.167em}}km of fiber using highly efficient superconducting nanowire single-photon detectors},
	journal = {Optica}
}" | betterbib - out.bib

100%|████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 74.35it/s]

Total number of entries: 1
Found: 1
Traceback (most recent call last):
  File "/Users/leofang/miniconda3/envs/qutip-env/lib/python3.6/site-packages/latexcodec/codec.py", line 715, in _get_latex_bytes_tokens_from_char
    return self.table.latex_map[c]
KeyError: '\u2009'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leofang/miniconda3/envs/qutip-env/lib/python3.6/site-packages/latexcodec/lexer.py", line 477, in encode
    self.get_latex_bytes(unicode_, final=final))
  File "/Users/leofang/miniconda3/envs/qutip-env/lib/python3.6/site-packages/latexcodec/codec.py", line 751, in get_latex_bytes
    bytes_, tokens = self._get_latex_bytes_tokens_from_char(c)
  File "/Users/leofang/miniconda3/envs/qutip-env/lib/python3.6/site-packages/latexcodec/codec.py", line 724, in _get_latex_bytes_tokens_from_char
    .format(repr(c)))
UnicodeEncodeError: 'latex' codec can't encode character '\u2009' in position 0: don't know how to translate '\u2009' into latex

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leofang/miniconda3/envs/qutip-env/bin/betterbib", line 10, in <module>
    sys.exit(main())
  File "/Users/leofang/miniconda3/envs/qutip-env/lib/python3.6/site-packages/betterbib/cli/full.py", line 35, in main
    tools.write(d, args.outfile, args.delimeter_type, tab_indent=args.tab_indent)
  File "/Users/leofang/miniconda3/envs/qutip-env/lib/python3.6/site-packages/betterbib/tools.py", line 372, in write
    for bib_id, d in od.items()
  File "/Users/leofang/miniconda3/envs/qutip-env/lib/python3.6/site-packages/betterbib/tools.py", line 372, in <listcomp>
    for bib_id, d in od.items()
  File "/Users/leofang/miniconda3/envs/qutip-env/lib/python3.6/site-packages/betterbib/tools.py", line 222, in pybtex_to_bibtex_string
    value = codecs.encode(value, "ulatex")
  File "/Users/leofang/miniconda3/envs/qutip-env/lib/python3.6/site-packages/latexcodec/codec.py", line 827, in encode
    encoder.encode(unicode_, final=True),
  File "/Users/leofang/miniconda3/envs/qutip-env/lib/python3.6/site-packages/latexcodec/lexer.py", line 481, in encode
    raise ValueError(e)
ValueError: 'latex' codec can't encode character '\u2009' in position 0: don't know how to translate '\u2009' into latex
```

It seems the author field caused the problem (one can try removing other fields), but I'm not sure what's wrong. It doesn't seem to contain any unicode character.

**Comment by nschloe** [comment]
Upstream issue https://github.com/mcmtroffaes/latexcodec/issues/68. I'll work around it.

**Comment by mcmtroffaes** [comment]
Just to note that I've just uploaded a new release for latexcodec, including a fix for this. Thanks again for reporting these issues upstream.

**Comment by leofang** [comment]
Thank you very much @nschloe and @mcmtroffaes for quick response! I did see the issue on `\u2010` but I wasn't sure whether I should raise the issue here or in the upstream.
