### ISSUE TITLE
Catch errors with broken author field

### ISSUE THREAD

**Issue by PRemmen** [nschloe/betterbib#135]
I have a large bibtex file, where several author fileds are not valid, some examples are:

```latex
author = {{Test, Author}}

author = {unknown}

author = {testfile.pdf}
```

betterbib does have some issues with these author fields (which is probably wanted!). However, for other broken entries (e. g. missing bibtex key) I get a very precise error message also indicating which line of my bibtex file is borken. 

I think it would be of great value if such a precise error message would be raised for these kinds of errors.

Traceback of the error is:

```python

Traceback (most recent call last):
  File "/home/.../bin/betterbib", line 10, in <module>
    sys.exit(main())
  File "/home/.../lib/python3.7/site-packages/betterbib/cli/full.py", line 32, in main
    tools.write(d, args.outfile, args.delimeter_type, tab_indent=args.tab_indent)
  File "/home/.../lib/python3.7/site-packages/betterbib/tools.py", line 375, in write
    for bib_id, d in od.items()
  File "/home/.../lib/python3.7/site-packages/betterbib/tools.py", line 375, in <listcomp>
    for bib_id, d in od.items()
  File "/home/.../lib/python3.7/site-packages/betterbib/tools.py", line 194, in pybtex_to_bibtex_string
    persons_str = " and ".join([_get_person_str(p) for p in persons])
  File "/home/.../lib/python3.7/site-packages/betterbib/tools.py", line 194, in <listcomp>
    persons_str = " and ".join([_get_person_str(p) for p in persons])
  File "/home/.../lib/python3.7/site-packages/betterbib/tools.py", line 289, in _get_person_str
    _join_abbreviated_names(p.first_names + p.middle_names),
  File "/home/.../lib/python3.7/site-packages/betterbib/tools.py", line 269, in _join_abbreviated_names
    out = lst[0]
IndexError: list index out of range
```

```shell
pip show betterbib
Name: betterbib
Version: 3.5.1
Summary: Better BibTeX data
Home-page: https://github.com/nschloe/betterbib
Author: Nico Schlömer
Author-email: nico.schloemer@gmail.com
License: License :: OSI Approved :: MIT License
Location: /home/.../lib/python3.7/site-packages
Requires: requests, tqdm, pybtex, appdirs, requests-cache, pyenchant, latexcodec
Required-by: 
```

**Comment by nschloe** [comment]
I can't reproduce this so maybe it has accidentally been fixed. If not, feel free to reopen with the offending bibtex entry.
