### ISSUE TITLE
special characters in titles etc.

### ISSUE THREAD

**Issue by mjlosch** [nschloe/betterbib#136]
Following up on the closed issue #97 I can provide a (hopefully) reproducible example with a file ttt.bib that only contains the following entry (with an asterisk "*" in the title):
```
@Article{cam:08,
  author =	 {Campin, J.-M. and J. Marshall and D. Ferreira},
  title =	 {Sea-Ice Ocean Coupling Using a Rescaled Vertical
                  Coordinate $z^\ast$}},
  journal =	 {Ocean Modelling},
  volume =	 24,
  number =	 {1--2},
  pages =	 {1--14},
  doi =		 {10.1016/j.ocemod.2008.05.005},
  year =	 2008
}
```
running betterbib-sync on this file gives:
```
myshell::> betterbib-sync ttt.bib
echo 'completed usercustomize.py 3.7'

100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 112.33it/s]


Total number of entries: 1
Found: 1
Traceback (most recent call last):
  File "/Users/mlosch/miniconda3/lib/python3.7/site-packages/latexcodec/codec.py", line 716, in _get_latex_bytes_tokens_from_char
    return self.table.latex_map[c]
KeyError: '∗'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mlosch/miniconda3/lib/python3.7/site-packages/latexcodec/lexer.py", line 477, in encode
    self.get_latex_bytes(unicode_, final=final))
  File "/Users/mlosch/miniconda3/lib/python3.7/site-packages/latexcodec/codec.py", line 752, in get_latex_bytes
    bytes_, tokens = self._get_latex_bytes_tokens_from_char(c)
  File "/Users/mlosch/miniconda3/lib/python3.7/site-packages/latexcodec/codec.py", line 725, in _get_latex_bytes_tokens_from_char
    .format(repr(c)))
UnicodeEncodeError: 'latex' codec can't encode character '\u2217' in position 0: don't know how to translate '∗' into latex

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mlosch/miniconda3/bin/betterbib-sync", line 10, in <module>
    sys.exit(main())
  File "/Users/mlosch/miniconda3/lib/python3.7/site-packages/betterbib/cli/sync.py", line 25, in main
    write(out, args.outfile, "braces", tab_indent=False)
  File "/Users/mlosch/miniconda3/lib/python3.7/site-packages/betterbib/tools.py", line 368, in write
    for bib_id, d in od.items()
  File "/Users/mlosch/miniconda3/lib/python3.7/site-packages/betterbib/tools.py", line 368, in <listcomp>
    for bib_id, d in od.items()
  File "/Users/mlosch/miniconda3/lib/python3.7/site-packages/betterbib/tools.py", line 218, in pybtex_to_bibtex_string
    value = codecs.encode(value, "ulatex")
  File "/Users/mlosch/miniconda3/lib/python3.7/site-packages/latexcodec/codec.py", line 828, in encode
    encoder.encode(unicode_, final=True),
  File "/Users/mlosch/miniconda3/lib/python3.7/site-packages/latexcodec/lexer.py", line 481, in encode
    raise ValueError(e)
ValueError: 'latex' codec can't encode character '\u2217' in position 0: don't know how to translate '∗' into latex
```

The problem persists, if one removes the ``\ast`` or even the entire title field, because the title appears to be fetched from the online-data base anyway. This happens on an Ubuntu System and on a MacBook with MacOS 10.13.6 (High Sierra)

I have not found a workaround or solution, yet.

**Comment by nschloe** [comment]
Fixed in 3.5.2.
