### ISSUE TITLE
Crash on first attempt

### ISSUE THREAD

**Issue by andreaferretti** [nschloe/betterbib#138]
I just tried betterbib (installed trhough pip), and found

```
Traceback (most recent call last):
  File "/Users/andrea/.bin/miniconda3/bin/betterbib", line 10, in <module>
    sys.exit(main())
  File "/Users/andrea/.bin/miniconda3/lib/python3.6/site-packages/betterbib/cli/full.py", line 28, in main
    d = sync(d, args.source, args.long_journal_names, args.num_concurrent_requests)
  File "/Users/andrea/.bin/miniconda3/lib/python3.6/site-packages/betterbib/sync.py", line 28, in sync
    data = future.result()
  File "/Users/andrea/.bin/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Users/andrea/.bin/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/andrea/.bin/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/andrea/.bin/miniconda3/lib/python3.6/site-packages/betterbib/crossref.py", line 170, in find_unique
    return self._crossref_to_pybtex(heuristic_unique_result(results, d))
  File "/Users/andrea/.bin/miniconda3/lib/python3.6/site-packages/betterbib/crossref.py", line 258, in _crossref_to_pybtex
    bibtex_type = self._crossref_to_bibtex_type(data)
  File "/Users/andrea/.bin/miniconda3/lib/python3.6/site-packages/betterbib/crossref.py", line 91, in _crossref_to_bibtex_type
    return _crossref_to_bibtex_type[crossref_type]
KeyError: 'reference-book'
```

Not sure what information can help you debug this issue

**Comment by nschloe** [comment]
I'll need the offending bibtex entry to reproduce this.

**Comment by andreaferretti** [comment]
After some bisection, I found that it crashes on just this entry:

```bib
@UNPUBLISHED{Darmon,
 author = {J. P. Serre},
 title = {Topics in Galois Theory},
 year = {1988},
 note = {Lecture notes by Henri Darmon, available at \url{http://www.ms.uky.edu/~sohum/ma561/notes/workspace/books/serre_galois_theory.pdf}}
}
```

**Comment by nschloe** [comment]
Whatever a `'reference-book'` is, it's now mapped to `@book` in bibtex. Hopefully that works for you.

**Comment by andreaferretti** [comment]
Thank you. Is this going to be released in pip? Or do you suggest an alternative way to install the master version?

**Comment by nschloe** [comment]
I already released it.

**Comment by andreaferretti** [comment]
Wow, that was fast! It does not show on https://pypi.org/project/betterbib/#history yet, but I will install as soon as they update their index :-) Thank you again!

**Comment by nschloe** [comment]
Try now.

**Comment by andreaferretti** [comment]
Thank you, now it installs fine!
