### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u011b' in position 114: character maps to <undefined>

### ISSUE THREAD

**Issue by ahfyzhang123** [nschloe/betterbib#152]
Hi,
Thanks for this betterbib.
I used the betterbib, it showed an error as following:
```
Traceback (most recent call last):
  File "d:\program files\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\program files\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python38\Scripts\betterbib.exe\__main__.py", line 7, in <module>
  File "d:\program files\python38\lib\site-packages\betterbib\cli\full.py", line 32, in main
    tools.write(d, args.outfile, args.delimeter_type, tab_indent=args.tab_indent)
  File "d:\program files\python38\lib\site-packages\betterbib\tools.py", line 419, in write
    file_handle.write("\n\n".join(segments) + "\n")
  File "d:\program files\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u011b' in position 114: character maps to <undefined>
```
Then, I tried to change 'file_handle.write("\n\n".join(segments) + "\n")' into 'file_handle.write("\n\n".join(segments) + "\n", encoding='utf-8')' in the tools.py. However, it showed the following:
```
Traceback (most recent call last):
  File "d:\program files\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\program files\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python38\Scripts\betterbib.exe\__main__.py", line 7, in <module>
  File "d:\program files\python38\lib\site-packages\betterbib\cli\full.py", line 32, in main
    tools.write(d, args.outfile, args.delimeter_type, tab_indent=args.tab_indent)
  File "d:\program files\python38\lib\site-packages\betterbib\tools.py", line 419, in write
    file_handle.write("\n\n".join(segments) + "\n", encoding='utf-8')
TypeError: write() takes no keyword arguments
```
The bib is following:
```
@article{bavzant1994nonlocal,
  title={Nonlocal damage theory based on micromechanics of crack interactions},
  author={Ba{\v{z}}ant, Zden{\v{e}}k P},
  journal={Journal of engineering mechanics},
  volume={120},
  number={3},
  pages={593--617},
  year={1994},
  publisher={American Society of Civil Engineers}
}
```
Now, I do not how to fixed it.

Many thanks.

Best.

**Comment by nschloe** [comment]
Cannot reproduce. With the bib you provide, I'm getting
```
@article{bavzant1994nonlocal,
 author = {Bažant, Zdeněk P.},
 title = {Nonlocal Damage Theory Based on Micromechanics of Crack Interactions},
 journal = {J. Eng. Mech.},
 volume = {120},
 number = {3},
 pages = {593-617},
 year = {1994},
 publisher = {American Society of Civil Engineers (ASCE)},
 doi = {10.1061/(asce)0733-9399(1994)120:3(593)},
 source = {Crossref},
 url = {https://doi.org/10.1061/(asce)0733-9399(1994)120:3(593)},
 issn = {0733-9399, 1943-7889},
 month = mar,
}
```
just fine.

**Comment by ahfyzhang123** [comment]
Thank you very much. I use the Win 10, python 3.8 (Python 3.8.2 (default, Apr  9 2020, 13:17:39)  [GCC 9.3.0 64 bit (AMD64)] on win32), and the betterbib 3.5.7 . Could you tell me the version that you use?

Many thanks.

Best.

**Comment by nschloe** [comment]
Linux, Python 3.8, betterbib 3.5.7.

**Comment by ahfyzhang123** [comment]
Thank you very much.

**Comment by nschloe** [comment]
Feel free to reopen if the issue persists.
