### ISSUE TITLE
pybtex.scanner.TokenRequired: syntax error

### ISSUE THREAD

**Issue by KuroRiposte** [nschloe/betterbib#167]
Hi, im currently getting this syntax error when attempting to perform betterbib on this entry.
```
@article{Van Essen_Donahue_Glasser_2018, title={Development and Evolution of Cerebral and Cerebellar Cortex}, ISSN={0006-8977}, DOI={10.1159/000489943}, abstractNote={Cerebral cortex and cerebellar cortex both vary enormously across species in their size and complexity of convolutions. We discuss the development and evolution of cortical structures in terms of anatomy and functional organization. We propose that the distinctive shapes of cerebral and cerebellar cortex can be explained by relatively few developmental processes, notably including mechanical tension along axons and dendrites. Regarding functional organization, we show how maps of myelin content in cerebral cortex are evolutionarily conserved across primates but differ in the proportion of cortex devoted to sensory, cognitive, and other functions. We summarize recent progress and challenges in (i) parcellating cerebral cortex into a mosaic of distinct areas, (ii) distinguishing cortical areas that correspond across species from those that are present in one species but not another, and (iii) using this information along with surface-based interspecies registration to gain deeper insights into cortical evolution. We also comment on the methodological challenges imposed by the differences in anatomical and functional organization of cerebellar cortex relative to cerebral cortex.}, journal={Brain, Behavior and Evolution}, author={Van Essen, D.C. and Donahue, C.J. and Glasser, M.F.}, year={2018}, pages={158–169} }
```
```
E:\04. thesis>betterbib reference.bib
```
```
Traceback (most recent call last):
  File "c:\users\shaun\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\shaun\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Shaun\anaconda3\Scripts\betterbib.exe\__main__.py", line 7, in <module>
  File "c:\users\shaun\anaconda3\lib\site-packages\betterbib\cli\full.py", line 17, in main
    data = bibtex.Parser().parse_file(args.infile)
  File "c:\users\shaun\anaconda3\lib\site-packages\pybtex\database\input\__init__.py", line 54, in parse_file
    self.parse_stream(f)
  File "c:\users\shaun\anaconda3\lib\site-packages\pybtex\database\input\bibtex.py", line 410, in parse_stream
    return self.parse_string(text)
  File "c:\users\shaun\anaconda3\lib\site-packages\pybtex\database\input\bibtex.py", line 397, in parse_string
    for entry in entry_iterator:
  File "c:\users\shaun\anaconda3\lib\site-packages\pybtex\database\input\bibtex.py", line 195, in parse_bibliography
    self.handle_error(error)
  File "c:\users\shaun\anaconda3\lib\site-packages\pybtex\database\input\bibtex.py", line 383, in handle_error
    report_error(error)
  File "c:\users\shaun\anaconda3\lib\site-packages\pybtex\errors.py", line 78, in report_error
    raise exception
  File "c:\users\shaun\anaconda3\lib\site-packages\pybtex\database\input\bibtex.py", line 193, in parse_bibliography
    yield tuple(self.parse_command())
  File "c:\users\shaun\anaconda3\lib\site-packages\pybtex\database\input\bibtex.py", line 226, in parse_command
    self.handle_error(error)
  File "c:\users\shaun\anaconda3\lib\site-packages\pybtex\database\input\bibtex.py", line 383, in handle_error
    report_error(error)
  File "c:\users\shaun\anaconda3\lib\site-packages\pybtex\errors.py", line 78, in report_error
    raise exception
  File "c:\users\shaun\anaconda3\lib\site-packages\pybtex\database\input\bibtex.py", line 223, in parse_command
    parse_body(body_end)
  File "c:\users\shaun\anaconda3\lib\site-packages\pybtex\database\input\bibtex.py", line 242, in parse_entry_body
    self.parse_entry_fields()
  File "c:\users\shaun\anaconda3\lib\site-packages\pybtex\database\input\bibtex.py", line 250, in parse_entry_fields
    self.parse_field()
  File "c:\users\shaun\anaconda3\lib\site-packages\pybtex\database\input\bibtex.py", line 262, in parse_field
    self.required([self.EQUALS])
  File "c:\users\shaun\anaconda3\lib\site-packages\pybtex\scanner.py", line 120, in required
    raise TokenRequired(description, self)
pybtex.scanner.TokenRequired: syntax error in line 490: '=' expected`
```
There seems to have no faulty characters that would generate typical syntax error in the .bib file for that entry, so I am not too sure what is causing this problem.

**Comment by nschloe** [comment]
The key has a space, that probably isn't valid bibtex.
