### ISSUE TITLE
KeyError: 'dissertation'

### ISSUE THREAD

**Issue by RaulDurand** [nschloe/betterbib#168]
Hi,

I recently got this error message:

```
Syncing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━  87% 0:00:05
Traceback (most recent call last):
  File "/usr/local/bin/betterbib", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/betterbib/cli/full.py", line 24, in main
    d = sync(d, args.source, args.long_journal_names, args.num_concurrent_requests)
  File "/usr/local/lib/python3.8/dist-packages/betterbib/sync.py", line 29, in sync
    data = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/betterbib/crossref.py", line 174, in find_unique
    return self._crossref_to_pybtex(heuristic_unique_result(results, d))
  File "/usr/local/lib/python3.8/dist-packages/betterbib/crossref.py", line 261, in _crossref_to_pybtex
    bibtex_type = self._crossref_to_bibtex_type(data)
  File "/usr/local/lib/python3.8/dist-packages/betterbib/crossref.py", line 95, in _crossref_to_bibtex_type
    return _crossref_to_bibtex_type[crossref_type]
KeyError: 'dissertation'
```

**Comment by nschloe** [comment]
What's the offending bi text entry?

**Comment by RaulDurand** [comment]
@nschloe, it is a big bibtex file. None of the entries has the @dissertation key. How do I find the offending entry?

**Comment by nschloe** [comment]
Bisecting.

**Comment by RaulDurand** [comment]
Ok. I'll need some time. A log option would be nice.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen with the offending bibtex entry.
