### ISSUE TITLE
Better handling of invalid doi in betterbib-doi2bibtex

### ISSUE THREAD

**Issue by gerstorfer** [nschloe/betterbib#172]
When `betterbib-doi2bibtex` encounters an invaild DOI it throws this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/betterbib-doi2bibtex", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/betterbib/cli/doi2bibtex.py", line 25, in main
    entry = source.get_by_doi(args.doi)
  File "/usr/local/lib/python3.9/site-packages/betterbib/crossref.py", line 104, in get_by_doi
    assert r.ok
AssertionError
```

It would be nice if this was replaced by a more intelligible error message

**Comment by nschloe** [comment]
Thanks for the report. Fixed now.

**Comment by gerstorfer** [comment]
It's better now and says:

```
Traceback (most recent call last):
  File "/usr/local/bin/betterbib-doi2bibtex", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/betterbib/cli/doi2bibtex.py", line 25, in main
    entry = source.get_by_doi(args.doi)
  File "/usr/local/lib/python3.9/site-packages/betterbib/crossref.py", line 101, in get_by_doi
    raise HttpError(f"Failed request to {self.api_url}")
betterbib.errors.HttpError: Failed request to https://api.crossref.org/works
```

But can't it say something like: "Error: Can't find DOI" instead of the Traceback?

**Comment by nschloe** [comment]
You mean to adapt the error message to the HTTP status code? Sure, that's possible too. If you prepare a PR, I'll be happy to take a look!
