### ISSUE TITLE
Assertion error on particular bibentry

### ISSUE THREAD

**Issue by blechta** [nschloe/betterbib#22]
With

```
@incollection{Bonito2011305,
  title =        "Viscoelastic Flows with Complex Free Surfaces: Numerical Analysis and Simulation",
  editor =       "R. Glowinski and J. Xu",
  booktitle =    "Numerical Methods for Non-Newtonian Fluids",
  publisher =    "Elsevier",
  year =         2011,
  volume =       16,
  pages =        "305 - 369",
  series =       "Handbook of Numerical Analysis ",
  issn =         "1570-8659",
  doi =          "10.1016/B978-0-444-53047-9.00003-4",
  url =          "http://www.sciencedirect.com/science/article/pii/B9780444530479000034",
  author =       "Andrea Bonito and Philippe Clément and Marco Picasso"
}
```

and master I get

```
Traceback (most recent call last):
  File "/home/jan/.local/bin/betterbib", line 99, in <module>
    _main()
  File "/home/jan/.local/bin/betterbib", line 48, in _main
    result = source.find_unique(entry)
  File "/home/jan/.local/lib/python2.7/site-packages/betterbib/crossref.py", line 176, in find_unique
    return self._crossref_to_pybtex(results[0])
  File "/home/jan/.local/lib/python2.7/site-packages/betterbib/crossref.py", line 237, in _crossref_to_pybtex
    bibtex_type = self._crossref_to_bibtex_type(data)
  File "/home/jan/.local/lib/python2.7/site-packages/betterbib/crossref.py", line 42, in _crossref_to_bibtex_type
    assert r.ok
AssertionError
```
```

**Comment by nschloe** [comment]
Fixed. (Release imminent.)
