### ISSUE TITLE
Index error on a particular bibentry

### ISSUE THREAD

**Issue by blechta** [nschloe/betterbib#23]
With

```
@Article{	  acharya.a:on,
  year		= {1999},
  issn		= {0374-3535},
  journal	= {Journal of Elasticity},
  volume	= {56},
  number	= {2},
  doi		= {10.1023/A:1007653400249},
  title		= {On compatibility conditions for the left {C}auchy--{G}reen
		  deformation field in three dimensions},
  publisher	= {Kluwer Academic Publishers},
  keywords	= {compatibility; left Cauchy-Green deformation; three
		  dimensions or (3-D)},
  author	= {Acharya, A.},
  pages		= {95--105},
  language	= {English}
}
```

and master I get

```
Traceback (most recent call last):
  File "/home/jan/.local/bin/betterbib", line 99, in <module>
    _main()
  File "/home/jan/.local/bin/betterbib", line 48, in _main
    result = source.find_unique(entry)
  File "/home/jan/.local/lib/python2.7/site-packages/betterbib/crossref.py", line 182, in find_unique
    return self._crossref_to_pybtex(result)
  File "/home/jan/.local/lib/python2.7/site-packages/betterbib/crossref.py", line 277, in _crossref_to_pybtex
    title = data['title'][0]
IndexError: list index out of range
```

**Comment by nschloe** [comment]
Ha, [crossref's data entry](https://api.crossref.org/v1/works/http://dx.doi.org/10.1023/a:1007653400249) doesn't have a title. There's zero data validation at crossref. :(

**Comment by nschloe** [comment]
Fixed. (Release imminent.)
