### ISSUE TITLE
more Python 3 Unicode 

### ISSUE THREAD

**Issue by thorade** [nschloe/betterbib#32]
The following entry 
```tex
@Article{Cigler2012,
  author  = {Cigler, Ji{\v{r}}{\'{i}} and Pr{\'{i}}vara, Samuel and V{\'{a}\v{n}}a, Zden{\v{e}}k and {\v{Z}}{\'{a}}{\v{c}}ekov{\'{a}}, Eva and Ferkl, Luk{\'{a}}{\v{s}}},
  title   = {Optimization of predicted mean vote index within model predictive control framework: Computationally tractable solution},
  journal = {Energy and Buildings},
  year    = {2012},
  volume  = {52},
  pages   = {39--49},
  doi     = {10.1016/j.enbuild.2012.05.022},
  issn    = {03787788}
}
```

gives the following error:
```
Reading from: refin2.bib
Saving to: refout.bib
|----------| 0/1   0% [elapsed: 00:00 left: ?, ? iters/sec]Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\subprocess.py", line 1170, in _readerthread
    buffer.append(fh.read())
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 176: character maps to <undefined>

Traceback (most recent call last):
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\Scripts\betterbib", line 98, in <module>
    _main()
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\Scripts\betterbib", line 48, in _main
    result = source.find_unique(entry)
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\betterbib\crossref.py", line 148, in find_unique
    payload = latex_to_unicode(' '.join(l)).replace(' ', '+')
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\betterbib\bibtex.py", line 15, in latex_to_unicode
    universal_newlines=True
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\subprocess.py", line 609, in check_output
    output, unused_err = process.communicate(inputdata, timeout=timeout)
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\subprocess.py", line 959, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\subprocess.py", line 1234, in _communicate
    stdout = stdout[0]
IndexError: list index out of range
```

Works in WinPython 2.7.9 on Windows, fails in WinPython 3.4 on Windows.

**Comment by nschloe** [comment]
Cannot reproduce in either Python 2 and 3. I'm getting
```
@article{Cigler2012,
  author = {Cigler, Jiří and Prívara, Samuel and Váňa, Zdeněk and Žáčeková, Eva and Ferkl, Lukáš},
  journal = {Energy and Buildings},
  title = {Optimization of Predicted Mean Vote index within Model Predictive Control framework: Computationally tractable solution},
  pages = {39-49},
  volume = {52},
  year = {2012},
  publisher = {Elsevier BV},
  source = {CrossRef},
  doi = {10.1016/j.enbuild.2012.05.022},
  url = {http://dx.doi.org/10.1016/j.enbuild.2012.05.022},
  month = sep
}
```
It seems to fail at `latex_to_unicode`. Do you have pandoc installed?

**Comment by thorade** [comment]
`pip list` says I have `pandoc (1.0.0b2)` installed.
Did you try to reproduce on Windows or Linux?

**Comment by nschloe** [comment]
I suspect Windows-only. Does
```
$ echo \\\"abc | pandoc -f latex -t plain
äbc
```
work for you on the command line?

**Comment by thorade** [comment]
That command returns `\\\"abc | pandoc -f latex -t plain` so I guess I am doing something wrong.

pandoc -h shows the pandoc help, so it is available on the command prompt.

**Comment by nschloe** [comment]
Hm, I don't know much about the Windows command line. Perhaps pipes (`|`) aren't available here.

**Comment by thorade** [comment]
I once had a similar error and the fix was to specify the encoding,
so to the betterbib script change line 29 to 
```python
out = open(args.outfile, mode='w', encoding="utf-8")
```
and to keep it Py2 compatible, add
```python
from io import open
```

But that does not seem to fix the problem here

**Comment by nschloe** [comment]
Nope, the problem is in `latex_to_unicode` which doesn't seem to do its job in Windows. No idea why.

**Comment by thorade** [comment]
Here is a small test script:
```python
import sys
from betterbib import bibtex
print(sys.version)
laStr = '\\\"abc $\sigma_4$'
unStr = bibtex.latex_to_unicode(laStr)
print(unStr)
```
returns `äbc σ~4~` on Python 2.7.9
returns `Ã¤bc Ïƒ~4~` on Python 3.4.2

**Comment by nschloe** [comment]
I'm getting
```
2.7.12+ (default, Sep 17 2016, 12:08:02) 
[GCC 6.2.0 20160914]
äbc σ₄
```
```
3.5.2+ (default, Sep 22 2016, 12:18:14) 
[GCC 6.2.0 20160927]
äbc σ₄

```
It's funny how the subscript is handles for you.

**Comment by nschloe** [comment]
@thorade What does this
```python
import pypandoc
out = pypandoc.convert_text('\\\"abc', 'plain', format='latex')
print(out)
```
do for you?

**Comment by thorade** [comment]
Sorry for answering late.
I changed the input to
```python
import sys
from betterbib import bibtex
import pypandoc
print(sys.platform)
print(sys.version)
out = pypandoc.convert_text('\\\"abc', 'plain', format='latex')
print(out)
```
The output is for WinPython 2.7
```
win32
2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
äbc
```
and for WinPython 3.5
```
win32
3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
äbc
```

**Comment by nschloe** [comment]
That's an improvement then. I'll add pypandoc to the dependencies.

**Comment by thorade** [comment]
Thanks, that almost fixes it, but now I get a Unicode error, and the fix is to specify explicitly the encoding on Windows (which does not use utf-8 by default).
I have sent a pull request that fixes it for me.
