### ISSUE TITLE
ValueError: Unknown type 'misc'

### ISSUE THREAD

**Issue by thorade** [nschloe/betterbib#40]
The following entry:
```tex
@misc{laine2010energy,
  title = {Energy and Thermal Performance Management Through Utilisation of Building Information Models},
  author = {Laine, Tuomas and Oy, Olof Granlund and Karola, Antti},
  year = {2010}
}
```
gives me the error:
```
Reading from: refin.bib
Saving to: refout.bib
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\mthorade\Documents\Python\WinPython-32bit-3.5.1.2\python-3.5.1\Scripts\betterbib", line 100, in <module>
    _main()
  File "C:\Users\mthorade\Documents\Python\WinPython-32bit-3.5.1.2\python-3.5.1\Scripts\betterbib", line 52, in _main
    result = source.find_unique(entry)
  File "C:\Users\mthorade\Documents\Python\WinPython-32bit-3.5.1.2\python-3.5.1\lib\site-packages\betterbib\crossref.py", line 176, in find_unique
    return self._crossref_to_pybtex(results[0])
  File "C:\Users\mthorade\Documents\Python\WinPython-32bit-3.5.1.2\python-3.5.1\lib\site-packages\betterbib\crossref.py", line 347, in _crossref_to_pybtex
    raise ValueError('Unknown type \'%s\'' % bibtex_type)
ValueError: Unknown type 'misc'
```
Where unknown type misc is misleading, as other misc entries work just fine (besides not being found on creossref).

**Comment by thorade** [comment]
Same error for this entry:
```tex
@misc{hesmos_hesmos_2013,
  title = {{HESMOS} - {Virtual} {Energy} {Lab}},
  url = {http://hesmos.eu/},
  urldate = {2015-03-11},
  journal = {ICT Platform for Holistic Energy Efficiency Simulation and Lifecycle Management Of Public Use Facilities},
  author = {HESMOS},
  year = {2013}
}
```

**Comment by nschloe** [comment]
I'm not really sure how to handle the `@misc` entries; perhaps those should be skipped altogether. The second example `hesmos_hesmos_2013` seems a little suspicious -- it has a journal, but isn't an article?

**Comment by nschloe** [comment]
Alright, so the two entries above now work on master; I'll release in a few minutes.

It's key that `@misc` entries cannot be found since it's unclear then what CrossRef's `container` then is: The journal, the book, something else perhaps? In any case, `@misc` is mostly websites and the like, things that cannot be found on CrossRef anyways, so no harm done here.

That brings to mind of course another possible correction that betterbib could provide: The entry type. That's for another time though.
