### ISSUE TITLE
betterbib crashes on some items

### ISSUE THREAD

**Issue by elandx** [nschloe/betterbib#43]
Hi i'm quite impressed how the `betterbib` works. But i have a trouble with dozen of entries, e.g.
```
@article{Arendt:2003,
    author  = {Detlev Arendt},
    journal = {Int. J. Dev. Biol},
    year    = {2003},
    volume  = {47},
    pages   = {563--571},
    langid  = {english},
    title   = {Evolution of eyes and photoreceptor cell types},
}
```
the `betterbib` produces such output:
```
▶ betterbib arendt.bib arendt-b.bib                                                                                                        
Reading from: arendt.bib
Saving to: arendt-b.bib
  0%|                                                                                                                 | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/elk/.local/bin/betterbib", line 97, in <module>
    _main()
  File "/home/elk/.local/bin/betterbib", line 49, in _main
    result = source.find_unique(entry)
  File "/home/elk/.local/lib/python3.5/site-packages/betterbib/crossref.py", line 188, in find_unique
    if result['title'][0].lower() in d['title'].lower():
IndexError: list index out of range
```
i am noticed that with the `journal` string removed it passed
what is wrong  with this bibitem?
Thanks in advance

**Comment by nschloe** [comment]
Thanks for the report; a fix is released.

**Comment by elandx** [comment]
Thanks a lot. Now it works as expected!
