### ISSUE TITLE
Add tool for journal name abbreviation

### ISSUE THREAD

**Issue by nschloe** [nschloe/betterbib#51]
BibTeX databases are often inconsistent in that some entries contain full journal names, some other abbreviated ones. This could be made consistent with a command-line tool.

Once Crossref's journal data reports the short name,
```
curl https://api.crossref.org/journals/0895-4798
```
this could be implemented.

**Comment by Edenharder** [comment]
Is it possible to change to another source to do the abbreviation? For example, [this one](https://raw.githubusercontent.com/JabRef/jabref/master/src/main/resources/journals/journalList.txt). The current abbreviation source does not contain `Physics Letters A` and some other journals.

**Comment by nschloe** [comment]
@Edenharder That's an awesome list! I'll certainly be able to include into betterbib.

**Comment by nschloe** [comment]
> It seems that the abbreviation of the journal can be done without sync other parts of the items, for example, this python script. Is it possible to separate the functionality "the abbreviation of the journal" from betterbib-sync?

Not really. The thing is that some online sources provide two journal name options (full and abbreviated), so you'll have to make a choice when running sync anyways. What I could do is provide an extra tool that only handles journal name abbreviations. Is this what you'd like?

**Comment by Edenharder** [comment]
@nschloe 

> What I could do is provide an extra tool that only handles journal name abbreviations. Is this what you'd like?

Yes! Great!

**Comment by nschloe** [comment]
There's now
```
betterbib-journal-abbrev
```
Update & enjoy!

**Comment by Edenharder** [comment]
@nschloe please check this command is already included. It gives the following error when I run `betterbib -h`
```
/usr/local/bin/betterbib: line 3: betterbib-journal-abbrev: command not found
usage: betterbib-format [-h] [-v] [-b] [-t] [-d {braces,quotes}]
                        [-u {unchanged,new,short}]
                        [infile] [outfile]
betterbib-format: error: argument outfile: can't open '': [Errno 2] No such file or directory: ''
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by nschloe** [comment]
Try again please.

**Comment by Edenharder** [comment]
```
betterbib -h
usage: betterbib-format [-h] [-v] [-b] [-t] [-d {braces,quotes}]
                        [-u {unchanged,new,short}]
                        [infile] [outfile]
betterbib-format: error: argument outfile: can't open '': [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/usr/local/bin/betterbib-journal-abbrev", line 85, in <module>
    _main()
  File "/usr/local/bin/betterbib-journal-abbrev", line 21, in _main
    for entry in data:
TypeError: 'BibliographyData' object is not iterable
```

**Comment by nschloe** [comment]
`betterbib` itself doesn't have `-h`. I should perhaps intercept that. Just`
```
betterbib in.bib out.bib
```

**Comment by Edenharder** [comment]
```
betterbib-journal-abbrev reference.bib out.bib
Traceback (most recent call last):
  File "/usr/local/bin/betterbib-journal-abbrev", line 85, in <module>
    _main()
  File "/usr/local/bin/betterbib-journal-abbrev", line 21, in _main
    for entry in data:
TypeError: 'BibliographyData' object is not iterable
```
and
```
betterbib reference.bib out.bib
100%|█████████████████████████████████████████████████████| 33/33 [00:26<00:00,  1.25it/s]
Traceback (most recent call last):
  File "/usr/local/bin/betterbib-journal-abbrev", line 85, in <module>
    _main()
  File "/usr/local/bin/betterbib-journal-abbrev", line 21, in _main
    for entry in data:
TypeError: 'BibliographyData' object is not iterable
```

**Comment by nschloe** [comment]
Rinse & repeat. :)

**Comment by Edenharder** [comment]
Great! Thanks! It works now.
