### ISSUE TITLE
skipping malformed references?

### ISSUE THREAD

**Issue by stzellerhoff** [nschloe/betterbib#54]
Is it possible to skip malformed references inside a bibtex file and continue with the next one instead of aborting the crossref query?

Thanks in advance!

Stephan

**Comment by nschloe** [comment]
Sounds good to me. Do you have a small example bibtex with a malformed entry?

**Comment by stzellerhoff** [comment]
Hi!

An example:

`@article{Sommer20128758,
        author = {Sommer, P., Kumar, G., Lipchik, Patel, J. J.},
        journal = {Ther. Adv. Respir. Dis},
        pages = {48--52},
        title = {Tracheobronchial amyloidosis managed with multimodality therapies},
        volume = {8},
        year = {2014},
}`

Error by betterbib:

`Traceback (most recent call last):
  File "/usr/local/bin/betterbib", line 102, in <module>
    _main()
  File "/usr/local/bin/betterbib", line 23, in _main
    data = parser.parse_file(infile)
  File "build/bdist.macosx-10.11-x86_64/egg/pybtex/database/input/__init__.py", line 51, in parse_file
  File "build/bdist.macosx-10.11-x86_64/egg/pybtex/database/input/bibtex.py", line 385, in parse_stream
  File "build/bdist.macosx-10.11-x86_64/egg/pybtex/database/input/bibtex.py", line 380, in parse_string
  File "build/bdist.macosx-10.11-x86_64/egg/pybtex/database/input/bibtex.py", line 344, in process_entry
  File "build/bdist.macosx-10.11-x86_64/egg/pybtex/database/__init__.py", line 547, in __init__
  File "build/bdist.macosx-10.11-x86_64/egg/pybtex/database/__init__.py", line 674, in _parse_string
  File "build/bdist.macosx-10.11-x86_64/egg/pybtex/errors.py", line 77, in report_error
pybtex.database.InvalidNameString: Too many commas in u'Sommer, P., Kumar, G., Lipchik, Patel, J.\xa0J.'`

I try to query crossref using betterbib on bibtex file generated by cermine. The bibtex output is not correct since authors a separated by commas (e.g. Smith, A, Doe, J, Miller A) and not by "and". Using sed, I can usually fix that, but some of the references like the one above show other problems...

**Comment by nschloe** [comment]
Ah, yes, I see now. This is going to be tougher to deal with; the error doesn't happen in betterbib itself, but in pybtex, a dependency used for parsing the bibtex. I'll check with their devs if we can do something about it.

Thanks again for the nice suggestion!

**Comment by stzellerhoff** [comment]
Thanks for your help! Another question: Is it possible to keep the original sorting of the bibtex entries and not sort it according to the citekey?

**Comment by nschloe** [comment]
Good suggestion; I've implemented it now and made it the default behavior. If you still want to have a sorted output in the future, use the `-s` command line option.
