### ISSUE TITLE
ValueError: 'latex' codec can't encode character '\u2010' in position 0: don't know how to translate '‐' into latex

### ISSUE THREAD

**Issue by chengs** [nschloe/betterbib#98]
ValueError: 'latex' codec can't encode character '\u2010' in position 0: don't know how to translate '‐' into latex

**Comment by nschloe** [comment]
What's the bibtex entry that generates the error?

**Comment by chengs** [comment]
Hello @nschloe 

```
@article{ha2012tube,
 author = {Ha, Sangtae and Sen, Soumya and Joe-Wong, Carlee and Im, Youngbin and Chiang, Mung},
 title = {Tube: {{Time}-dependent} pricing for mobile data},
 journal = {ACM SIGCOMM Computer Communication Review},
 volume = {42},
 number = {4},
 pages = {247},
 year = {2012},
 publisher = {ACM},
 doi = {10.1145/2377677.2377723},
 source = {Crossref},
 url = {https://doi.org/10.1145/2377677.2377723},
 issn = {0146-4833},
 month = sep,
}

@article{gorski2005healpix,
 author = {Gorski, K. M. and Hivon, E. and Banday, A. J. and Wandelt, B. D. and Hansen, F. K. and Reinecke, M. and Bartelmann, M.},
 title = {{HEALPix:} {A} Framework for High-Resolution Discretization and Fast Analysis of Data Distributed on the Sphere},
 journal = {ApJ},
 volume = {622},
 number = {2},
 pages = {759-771},
 year = {2005},
 publisher = {IOP Publishing},
 doi = {10.1086/427976},
 source = {Crossref},
 url = {https://doi.org/10.1086/427976},
 issn = {0004-637X, 1538-4357},
 month = apr,
}
```

The above example triggers two bugs.
1. The title is incomplete, only "Tube" remains and the rest is missing.
2. The '\u2010' crash.

Complete terminal output
```
Total number of entries: 2
Found: 2
Traceback (most recent call last):
  File "/Users/guchen/anaconda3/lib/python3.6/site-packages/latexcodec/codec.py", line 685, in _get_latex_bytes_tokens_from_char
    return self.table.latex_map[c]
KeyError: '‐'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/guchen/anaconda3/lib/python3.6/site-packages/latexcodec/lexer.py", line 479, in encode
    self.get_latex_bytes(unicode_, final=final))
  File "/Users/guchen/anaconda3/lib/python3.6/site-packages/latexcodec/codec.py", line 721, in get_latex_bytes
    bytes_, tokens = self._get_latex_bytes_tokens_from_char(c)
  File "/Users/guchen/anaconda3/lib/python3.6/site-packages/latexcodec/codec.py", line 694, in _get_latex_bytes_tokens_from_char
    .format(repr(c)))
UnicodeEncodeError: 'latex' codec can't encode character '\u2010' in position 0: don't know how to translate '‐' into latex

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/guchen/anaconda3/bin/betterbib-sync", line 4, in <module>
    __import__('pkg_resources').run_script('betterbib==3.2.0', 'betterbib-sync')
  File "/Users/guchen/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/guchen/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/Users/guchen/anaconda3/lib/python3.6/site-packages/betterbib-3.2.0-py3.6.egg/EGG-INFO/scripts/betterbib-sync", line 126, in <module>
    _main()
  File "/Users/guchen/anaconda3/lib/python3.6/site-packages/betterbib-3.2.0-py3.6.egg/EGG-INFO/scripts/betterbib-sync", line 40, in _main
    betterbib.write(od, args.outfile, 'braces', tab_indent=False)
  File "/Users/guchen/anaconda3/lib/python3.6/site-packages/betterbib-3.2.0-py3.6.egg/betterbib/tools.py", line 322, in write
    dictionary=dictionary,
  File "/Users/guchen/anaconda3/lib/python3.6/site-packages/betterbib-3.2.0-py3.6.egg/betterbib/tools.py", line 191, in pybtex_to_bibtex_string
    value = codecs.encode(value, 'ulatex')
  File "/Users/guchen/anaconda3/lib/python3.6/site-packages/latexcodec/codec.py", line 797, in encode
    encoder.encode(unicode_, final=True),
  File "/Users/guchen/anaconda3/lib/python3.6/site-packages/latexcodec/lexer.py", line 483, in encode
    raise ValueError(e)
ValueError: 'latex' codec can't encode character '\u2010' in position 0: don't know how to translate '‐' into latex
```

**Comment by chengs** [comment]
For the '\u2010' problem, I fix it by adding the following code in ./betterbib/tools.py since the line 187:
```python
        try:
            #fix
            if isinstance(value, str):
                value = value.replace('\u2010','-')
            value = codecs.encode(value, 'ulatex')
        except TypeError:
            # expected unicode for encode input, but got int instead
            pass
```
It works for me because I use python 3. For python 2, unfortunately, it won't... And I don't make a pull request since this fix is ugly. I am sure you can find a better way.

**Comment by nschloe** [comment]
Yeah, the title "tube" is unchanged because that appears to be the title of the article. At least [according to Crossref](https://search.crossref.org/?q=10.1145%2F2377677.2377723). If this is wrong, you could ping the crossref people on twitter and they'll fix it for you (and everyone else).

The second issue is really in the dependent package latexcodec; see https://github.com/mcmtroffaes/latexcodec/issues/56. Let's wait till the fix lands there.

**Comment by chengs** [comment]
well, at least in the title case, the user should be warned about this too much difference on the main properties. Don’t you think?

**Comment by nschloe** [comment]
Hm, not sure. There are people you just put a doi in there and rely on betterbib to populate the rest. Plus, it'd be hard to decide when exactly to _warn_ the user. I think I prefer the clarity of how things are handled now: Everything is overridden from online sources, the rest is up to you. Eventually, there has to be a human to check if all is correct, just like you did.

**Comment by chengs** [comment]
OK. The way you describe is never to me. So let it be. Thank you for replying.

**Comment by chengs** [comment]
Hello, regarding the incomplete title issue, I contacted the crossref. They said in their data, the missing part belongs to the "subtitle" column. For instance, for the "tube" pape, the following is in the xml (http://api.crossref.org/works/10.1145/2377677.2377723/transform/application/vnd.crossref.unixsd+xml)
```xml
<titles>
<title>TUBE</title>
<subtitle>time-dependent pricing for mobile data</subtitle>
</titles>
```
So, IMHO, both values in the "titles" shall be used to have a complete title.

**Comment by nschloe** [comment]
Hm, interesting! biblatex has the subtitle property, so I guess that's what we should use.

**Comment by nschloe** [comment]
Alright, I've now added support for subtitles. The parsed entry appears as
```
@article{ha2012tube,
 author = {Ha, Sangtae and Sen, Soumya and Joe-Wong, Carlee and Im, Youngbin and Chiang, Mung},
 title = {Tube},
 journal = {SIGCOMM Comput. Commun. Rev.},
 volume = {42},
 number = {4},
 pages = {247},
 year = {2012},
 publisher = {Association for Computing Machinery (ACM)},
 doi = {10.1145/2377677.2377723},
 source = {Crossref},
 url = {https://doi.org/10.1145/2377677.2377723},
 issn = {0146-4833},
 month = sep,
 subtitle = {time-dependent pricing for mobile data},
}
```
Now it depends on your bibtex style to use that information. Let me know, how it goes.

**Comment by chengs** [comment]
Unfortunately, in the "ieeetr" style (which i use the most), still only "tube" appears.
FYI, my tex is in the following
```tex
\documentclass{IEEEtran}
\begin{document}
	
\section{Hello}
Hello~\cite{ha2012tube}

\bibliographystyle{ieeetr}
\bibliography{test.bib}
\end{document}
```
test.bib has the "tube" paper.

**Comment by nschloe** [comment]
Yeah I thought this might happen. How about https://tex.stackexchange.com/a/100116/13262?

**Comment by chengs** [comment]
Yeah! Now it look far better!
<img width="478" alt="screen shot 2018-01-30 at 9 49 46 pm" src="https://user-images.githubusercontent.com/824529/35590556-874c9f9a-0607-11e8-97b2-c4ca8e982d6a.png">
